liip_imagine:
    driver: "gd"  # Le choix du pilote (gd, gmagick, imagick)

    filter_sets:
        miniature:
            quality: 75
            filters:
                thumbnail:
                    size: [400, 250]
                    mode: inset
